language: c
dist: bionic
sudo: required
git:
  depth: 1

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq --allow-unauthenticated
  - sudo apt-get install -y --allow-unauthenticated g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo apt-get install clang-3.8 fakeroot realpath
  - ./scripts/install-deps.sh -i -s
  - sudo apt-get autoremove
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100
  - export PATH=$PATH:`pwd`/deps/julia/bin
  - sudo updatedb
  - sudo ldconfig
  - git clone https://github.com/CxxTest/cxxtest.git
  - export PATH=$PATH:`pwd`/cxxtest/bin/; export LIBRARY_PATH=$LIBRARY_PATH:`pwd`/cxxtest/
before_script: mkdir -p ../tmp/x64 && mkdir -p ../tmp/asan
script:
  - bash -c "./waf distclean configure build &&
             ./waf distclean configure --use-all --use-third-party --use-dev --prefix=../tmp/x64 &&
             ./waf build &&
             ./waf install" &&
    bash -c "source ./examples/env $(realpath ../tmp/x64) &&
             ./waf build_examples &&
             ./waf build_tests &&
             ./build/tests/test/runner" &&
    bash -c "./waf distclean configure --use-all --use-third-party --use-dev --prefix=../tmp/asan &&
             ./waf build_asan &&
             ./waf install_asan" &&
    bash -c "source ./examples/env $(realpath ../tmp/asan) &&
             ./waf build_examples_asan &&
             ./waf build_tests_asan &&
             ./build/tests_asan/test/runner"
  - scripts/make_debian_package.sh

deploy:
  provider: releases
  api_key:
    secure: Hzbgqf3joHd18ngCJlP3pXn8q/dPUIuvvepQ9XWr3aGOXq68fP50mEToVeH50X+8E2OE8cv2WNLRhOXQNGxX5vGe1D75AckM+v8c3XynK2YXnQhvr4nHQNYaBXO6zbQY340Q7kLubHqCXl5uMZPOEyYePKjkSFdowYDKDprgrSXA/sUhZ+SEzMB4AS995PkyB9Vg+gFEHRrRkL2wPUu75isnP8pNP0VKdK6hpKZ1QvPhJVe0rUyO4KtR+sVbjTlky0QryGvqp5MyY+2px3z62gZvdyCN3DQhlg+ZMcAzk3612Kt3nZ7d9aGKB5bMl8aEZJxg4C94OdqfiwxrDjXo2UXfzEB+8OTTGHmmoAl026NnlRhw9wErO+Jh2YfJQ3EOxVoZ4qE5eKulBxbjZs35cN7wu05hLwPlgYzDjhlKpS3OBn/ch2T+PIBedxu/JqwDKpBRbiDEl0aa6hIkDbOyHlnwcuSN9oIOQlBV1cqt3gz4hFgLIEZ50rZTnSa+r2oGkESh+wyyKfcg1Hdk9OiGvqbOGROj2yLuLxkp9B2PgwxUHIhYMTQYlVZKqW7FRon9j0RF7AKxWuHqJIur0VTm+QxuN1oDLmrXoJ2eSqq6lSKRNC1jIf3EcYemgC0l15i75vJbYHeRs8yDOoOeWzJntObqvW1v57KS4U96babQvSk=
  file_glob: true
  file: build/*.deb
  skip_cleanup: true
  on:
    tags: true

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/e23128f14b1634065c82
        on_success: change
        on_failure: always
        on_start: never
    email:
        recipients:
            - jonathan.bendes@gmail.com
        on_success: change
        on_failure: always
        on_start: never
